import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
// import { getLocale } from "gt-next/server"; // Removed this import as it's likely no longer needed here
import { GTProvider } from "gt-next"; // Ensure this import is correct based on gt-next docs

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		// CHANGED: Removed lang attribute
		<html>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<GTProvider>
					<Navbar />
					{children}
					<Footer />
				</GTProvider>
			</body>
		</html>
	);
}